feat: add kafka tls flags
streamdal/plumber-schemas pull request #77
Opened 2022-09-19 05:49 UTC by dennisme

Adding required flags

2022-09-19 16:48 UTC, blinktag requested changes
Field IDs need to be unique in the message. The highest currently is sasl_password, so start after that and increment

2022-09-19 16:48 UTC, blinktag commented on protos/args/ps_args_kafka.proto
> +  bool tls_ca_cert = 3;
```suggestion
  bool tls_ca_cert = 8;
```

2022-09-19 16:48 UTC, blinktag commented on protos/args/ps_args_kafka.proto
> +  bool tls_client_cert = 3;
```suggestion
  bool tls_client_cert = 9;
```

2022-09-19 16:48 UTC, blinktag commented on protos/args/ps_args_kafka.proto
> +  bool tls_client_key = 3;
```suggestion
  bool tls_client_key = 10;
```

2022-09-23 16:49 UTC, dennisme commented on protos/args/ps_args_kafka.proto
> +  bool tls_ca_cert = 3;
oh yes

2022-09-24 17:05 UTC, dennisme commented
Believe this is failing because its on a fork.

2024-03-13 17:39 UTC, dselans commented
This is super old; closing.

2024-03-13 17:39 UTC, closed without merging